service: spark-joy

provider:
    name: aws
    runtime: nodejs14.x
    stage: ${opt:stage}
    environment:
        WIDGETS_TABLE: ${self:service}-widgets2-${self:provider.stage}
        FEEDBACKS_TABLE: ${self:service}-votes-${self:provider.stage}
    httpApi:
        cors: true
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.WIDGETS_TABLE}"
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FEEDBACKS_TABLE}"
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              - Fn::Join:
                    - ":"
                    - - arn:aws:secretsmanager
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - secret:*

functions:
    graphql:
        handler: dist/graphql.handler
        memorySize: 1024
        events:
            - httpApi:
                  path: /graphql
                  method: GET
                  cors: true
            - httpApi:
                  path: /graphql
                  method: POST
                  cors: true

    feedbackNotification:
        handler: dist/feedbackNotification.handler
        events:
            - stream:
                  type: dynamodb
                  arn:
                      Fn::GetAtt:
                          - JoyFeedbacksTable
                          - StreamArn
                  # we update records when users add answers
                  # hopefully this reduces noise
                  # (it didn't)
                  batchSize: 5
                  MaximumBatchingWindowInSeconds: 60

resources:
    Resources:
        JoyWidgetsTable:
            Type: "AWS::DynamoDB::Table"
            Properties:
                AttributeDefinitions:
                    - AttributeName: userId
                      AttributeType: S
                    - AttributeName: widgetId
                      AttributeType: S
                KeySchema:
                    - AttributeName: userId
                      KeyType: HASH
                    - AttributeName: widgetId
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.WIDGETS_TABLE}
        JoyFeedbacksTable:
            Type: "AWS::DynamoDB::Table"
            Properties:
                AttributeDefinitions:
                    - AttributeName: widgetId
                      AttributeType: S
                    - AttributeName: voteId
                      AttributeType: S
                KeySchema:
                    - AttributeName: widgetId
                      KeyType: HASH
                    - AttributeName: voteId
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.FEEDBACKS_TABLE}
                StreamSpecification:
                    StreamViewType: NEW_IMAGE
