name = "cloudflare-cf-backend"
type = "webpack"

account_id = ""
zone_id = ""
route = ""

workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2022-01-06"

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

[vars]
AWS_REGION = "us-east-1"

## Must match naming in backend/serverless.yml
[env.dev.vars]
WIDGETS_TABLE = "spark-joy-widgets2-dev"
FEEDBACKS_TABLE = "spark-joy-votes-dev"

## Must match naming in backend/serverless.yml
[env.production.vars]
WIDGETS_TABLE = "spark-joy-widgets2-prod"
FEEDBACKS_TABLE = "spark-joy-votes-prod"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"
